### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by probonopd** [vfrico/fontsquirrel_dl#1]
```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fontsquirrel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fontsquirrel.py", line 30, in <module>
    import urllib.request
ImportError: No module named request
```

**Comment by vfrico** [comment]
Please, could you try the same but using any Python version upper to 3.4?

Thanks!

**Comment by probonopd** [comment]
Works, thanks.
